name: CI

on:
  push:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build tool
      run: go build -v .
    
    - name: Run tests
      run: go test -v -race -timeout 10m ./...
    
    - name: Check go mod tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum
